### ISSUE TITLE
Possible client index mismatch during retry

### ISSUE THREAD

**Issue by Rainyan** [bauxiteDYS/SM-NT-REJOIN#1]
**edit: invalid; see comments below**

<details><summary>Original message (incorrect)</summary>

Currently, the plugin stores the client index as an identifier for the retry'ing client. Problem is, client indices are not unique, so if you have multiple people joining and/or leaving, the lowest free client index will be given to any client joining the server, and this is not guaranteed to be the same player who relinquished that index for the connection retry.

Consider the following empty server scenario:

```mermaid
graph TD;
        A(Client A)
        B(Client B)

        A--> |joins| C(Server)
        B--> |joins| C

        C--> |assigns first free index| D("Client A (holds index 1)")
        C--> |assigns first free index| E("Client B (holds index 2)")

        D--> |"disconnects; frees index 1"| F(client A)
        E--> |"disconnects; frees index 2"| G(client B)

        G--> |retries| C
```

This should illustrate how Client B can end up with Client A's old index if they disconnect simultaneously. Similarly, if clients join simultaneously, whoever joins quickest will get the lowest free index.

To get around this, you'll need some kind of unique identifier. Typically this would be the "userid", which is a unique integer that goes up by one for player who joins, but as you can't use this to track clients across re-joins (they'll get a new, bigger userid), you'll probably want to track them by their SteamID - `IsClientAuthorized` together with `GetSteamAccountID` or `GetClientAuthId` return useful values for this purpose. Another alternative could be the [Client Preferences API](https://wiki.alliedmods.net/Client_Preferences_API_(SourceMod)), but this might be overkill here.

To get even fancier, you could use the global forward `OnClientAuthorized` to check for any pending retries without needing the timer system - this also has the benefit of not having to check `IsClientAuthorized`:
```sp
public void OnClientAuthorized(int client, const char[] auth)
{
    /* IF HAS PENDING REJOIN(auth)... */
}
```

</details>

**Comment by bauxiteDYS** [comment]
You're fast, I knew there was something jank about the code, just didn't know what. Thanks.

**Comment by bauxiteDYS** [comment]
Any idea what this means, `Reconnect a client without dropping the netchannel`, when using the ReconnectClient() function. Does this mean that the user index might not change, or what is the effect of not dropping the net channel anyway?

**Comment by bauxiteDYS** [comment]
I did some experimentation and it seems the Client Index doesn't actually change when a client is forced to reconnect via ReconnectClient() function, from what I could tell.

**Comment by Rainyan** [comment]
Ok, this is embarassing but it seems "retry" does something similar to ReconnectClient behind the scenes, and indeed the index is kept the same, so this issue is basically invalid! This was based on my mistaken assumption about how connecting/reconnecting works. Sorry about the wild-goose chase.
